# Hotkey to open chat
hotkey: MpTextChatAll # T

# Number of messages to store
history_limit: 50

# Message template for non command messages
default_template: <h1><i class="fas fa-fw fa-star"></i> {0}</h1>{1}
